Feature/google&&facebook auth
krotosua/Clock_Project pull request #26
Opened 2022-07-25 06:29 UTC by krotosua

2022-07-27 11:49 UTC, X2Style requested changes

2022-07-27 11:49 UTC, X2Style commented on client_/public/index.html
> +    <script src="https://accounts.google.com/gsi/client" async defer></script>
А разве внутри пакета нет нужных методов?

2022-07-27 11:49 UTC, X2Style commented on client_/public/index.html
> +
Зачем отступы?

2022-07-27 11:49 UTC, X2Style commented on client_/src/pages/Auth.jsx
> +const GOOGLE_ID = "145403046222-om4k4l5svehljv6bee1bne9megjn84cc"
Может лучше в .env вынести?

2022-07-27 11:49 UTC, X2Style commented on server/businessLogic/masterLogic.ts
> +            console.log("tutatutSdas")
log

2022-07-27 11:49 UTC, X2Style commented on server/businessLogic/masterLogic.ts
> +            console.log(newMaster)
log

2022-07-27 11:49 UTC, X2Style commented on server/businessLogic/userLogic.ts
> +const base64url = require('b64url');
import?

2022-07-27 11:49 UTC, X2Style commented on server/controllers/masterController.ts
> +            console.log(cityIdes)
log

2022-07-27 11:49 UTC, X2Style commented on server/controllers/userController.ts
> +
empty line

2022-07-27 11:49 UTC, X2Style commented on server/package.json
> +    "b64url": "^1.0.3",
Какой из двух используется?

2022-07-27 11:49 UTC, X2Style commented on server/routes/userRouter.ts
> +
Empty line

2022-07-27 11:49 UTC, X2Style commented on server/server.ts
> +
Empty line

2022-07-28 10:30 UTC, X2Style requested changes

2022-07-28 10:30 UTC, X2Style commented on client_/public/index.html
> +    <script src="https://accounts.google.com/gsi/client"></script>
А разве внутри пакета нет нужных методов?

2022-07-28 10:30 UTC, X2Style commented on client_/src/asyncActions/users.jsx
> +            const dataUser = await googleAuth(dataGoogle, isMaster, cityList)
Можно отрефакторить и не повторять один и тот же блок 3 раза

2022-07-28 10:30 UTC, X2Style commented on server/businessLogic/userLogic.ts
> +    parse_signed_request(signed_request: any, secret: string) {
Везде camelCase, а тут почему-то campel_case

2022-07-28 13:29 UTC, krotosua commented on client_/public/index.html
> +    <script src="https://accounts.google.com/gsi/client"></script>
Пакет удалил - поскольку не использовал. Оставил данное подключение

2022-07-30 03:26 UTC, Aaaazzzzzzzz approved these changes

2022-08-01 19:38 UTC, X2Style requested changes

2022-08-01 19:38 UTC, X2Style commented on client_/public/index.html
> +    <script src="https://accounts.google.com/gsi/client"></script>
Тот же вопрос

2022-08-01 19:38 UTC, X2Style commented on client_/package.json
> +    "react-facebook-login": "^4.1.1",
Куда делся пакет с google login?

2022-08-10 13:26 UTC, X2Style requested changes

2022-08-10 13:26 UTC, X2Style commented on client_/src/components/authPageComponents/Login.jsx
> +    const responseGoogle = async (responseGoogle) => {
Мне кажется можно отрефакторить в один метод?

2022-08-10 13:26 UTC, X2Style commented on client_/src/pages/Auth.jsx
> +    const responseFacebook = async (responseFacebook) => {
Мне кажется, или что-то подобное я уже видел в [Login.jsx]?(https://github.com/krotosua/Clock_Project/pull/26/files#diff-3aaf406e6c6603833140c0ead79a3fbbb5c28b0ca612d43c7d1a90a03b114527)

2022-08-10 13:26 UTC, X2Style commented on server/businessLogic/userLogic.ts
> +    async googleAuth(req: Request, res: Response, next: NextFunction): Promise<void | Response<{ token: string }>> {
В этих методах тоже код по два раза, два раза. Можно отрефакторить?

2022-08-18 11:16 UTC, X2Style requested changes

2022-08-18 11:16 UTC, X2Style commented on client_/src/pages/Auth.jsx
> +                message: "Укажите город(а)"
Перевод?

2022-08-18 11:16 UTC, X2Style commented on client_/src/pages/Auth.jsx
> +                                                            isSame: value => dirtyFields?.passwordCheck && dirtyFields?.password ? value === getValues("password") || "Пароли не одинаковые" : null
Перевод?

2022-08-25 05:22 UTC, merged