add paypal customer
krotosua/Clock_Project pull request #31
Opened 2022-07-28 18:42 UTC by krotosua

2022-08-01 19:45 UTC, X2Style reviewed
[client_/src/components/customerPageComponents/OrderListCustomer.jsx](https://github.com/krotosua/Clock_Project/pull/31/files#diff-350f3839225cc5a21997c002315f3dcf1917bbc81377fc3900fbce8e25a41691) - его точно нужно удалять?

2022-08-01 19:45 UTC, X2Style commented on client_/src/components/customerPageComponents/PayPalModal.jsx
> +
Empty line

2022-08-02 13:47 UTC, krotosua commented
Точно надо удалять

2022-08-02 22:51 UTC, X2Style approved these changes

2022-08-02 22:52 UTC, X2Style requested changes

2022-08-02 22:52 UTC, X2Style commented on client_/src/components/orderPageComponents/PayPal.jsx
> +
Empty line

2022-08-03 06:48 UTC, krotosua commented
Компонент PayPal полностью сменит себя в google auth из-за внесенных правок

2022-08-18 11:06 UTC, X2Style requested changes

2022-08-18 11:06 UTC, X2Style commented on client_/src/pages/Customer.jsx
> +                                                              'Станет доступна после выполнения заказа'
Так как уже добавили мультиязычность, то можно ее тут уже использовать

2022-08-18 11:06 UTC, X2Style commented on client_/src/pages/Customer.jsx
> +                    <Tooltip title="Добавить заказ" placement="top" arrow>
Так как уже добавили мультиязычность, то можно ее тут уже использовать

2022-08-25 11:33 UTC, X2Style approved these changes

2022-08-25 11:40 UTC, X2Style approved these changes

2022-08-25 11:45 UTC, X2Style approved these changes

2022-08-25 12:01 UTC, merged